---
title: "380_Project"
author: "Abdallah Al Rahbi"
date: "2023-04-23"
output: pdf_document
---

## Front Matter

```{r}
packages <- c(
  "dplyr", 
  "readr", 
  "tidyr", 
  "purrr", 
  "broom",
  "magrittr",
  "corrplot",
  "caret",
  "rpart",
  "rpart.plot",
  "e1071",
  "torch", 
  "luz",
  "ramify",
  "stringr",
  "janitor",
  "reshape2",
  "ggpubr",
  "ggplot2"
)

# renv::install(packages)
sapply(packages, require, character.only=T)
```

## Data Cleaning

```{r}
owid <- read.csv("https://raw.githubusercontent.com/JackBenadon/Stat-380-group-project/main/owid-co2-data.csv")
goma <- read.csv("https://raw.githubusercontent.com/JackBenadon/Stat-380-group-project/main/GOMA.csv")
eo <- read.csv("https://raw.githubusercontent.com/JackBenadon/Stat-380-group-project/main/Table_7.1_Electricity_Overview.csv")
tran <- read.csv("https://raw.githubusercontent.com/JackBenadon/Stat-380-group-project/main/Trasportation%20data.csv")
```

```{r}
zowidyearly1800_2021 <- owid%>%
  select(c(country,year,co2,gdp,population))%>%
  filter(country=="United States")
zowideyearly2005_2022 <- zowidyearly1800_2021%>%
  filter(year>=2005)
goma$DATE <- as.Date(goma$DATE)
goma$year <- as.numeric(format(goma$DATE, "%Y"))
zGOMAYearly2005_2022 <- goma%>%
  filter(str_detect(DATE, "01-01"))
zeosmonthly1973_2022 <- eo[10:610,]
zeosmonthly1973_2022 <- zeosmonthly1973_2022%>%
  row_to_names(row_number = 1)
zeosmonthly1973_2022 <- zeosmonthly1973_2022[-c(1),]
zeosyearly1973_2022 <- zeosmonthly1973_2022%>%
  filter(str_detect(Month, "January"))
zeosyearly2005_2022 <- zeosyearly1973_2022
zeosyearly2005_2022$Month <- gsub("January","",zeosyearly2005_2022$Month)
zeosyearly2005_2022 <- zeosyearly2005_2022%>%
  filter(Month>=2005)
ztransyearly1990_2015 <- tran %>%
  select(-c(X,X.1,X.2,X.3,X.4,X.5)) %>%
  t() %>%
  as.data.frame() %>%
  row_to_names(row_number = 1) %>%
  clean_names()%>%
  select(-c(2,23))
```

-----
## Explotory Data Analysis

### OWID

We produced a line graph for the total yearly carbon dioxide emission in the United States from 2005 to 2021. 

From the graph, we found that the Carbon Dioxide emission is in steadily declining since 2005, which is a direct result of efforts made on reducing co2 emission since the recognition of global warming. There is a slight increase in emission in 2021. This aligns with the "Build America Buy America Act", a legislation made in the same year, stating that all construction material used for infrastructure must be manufactured in the united states. Also, after COVID-19, global trade was greatly hindered, and the need for reliable goods produced domestically increased.

```{r}
zzlowid2005_2021<- ggplot(zowideyearly2005_2022,aes(x=year,y=co2))+geom_line(color="darkblue")+theme_bw()+labs(title="United States Total Carbon Dioxide Emission 2005 - 2021", y= "CO2 Emission (Million Metric Tons)",x="Year")
zzlowid2005_2021
```

### GOMA

We produced a line graph for the Gross Manufacturing Output in the United States from 2005 to 2021.

From the graph, we found that the gross manufacturing output have increased roughly 55% since 2005, with slight dips in 2008, 2014, and 2020. This aligns with the global financial crisis, the energy crisis, and the COVID-19 pandemic respectively. It is speculated that this is due to the Manufacturing Enterprise Integration Act of 2002, which promoted the rise of smart manufacturing, and later digital manufacturing and robotic use. Data suggests that this act eliminated jobs, but increased the production capacity by a large margin.

```{R}
zzlgoma2005_2022 <- ggplot(zGOMAYearly2005_2022,aes(x=year,y=GOMA))+geom_line(color="red")+theme_bw()+labs(title="United States Gross Manufacturing Output 2005 - 2021", y= "Gross Manufacturing Output",x="Year")
zzlgoma2005_2022
```

### EO

We produced a line graph for the Gross Manufacturing Output in the United States from 2005 to 2021.

From the graph, we can see that there is no obvious trend observed for this variable, as the measure fluctuates between 317 million and 350 million kilowatt hours over the observed period. CO2 emission from the electricity sector is still extremely relevant, since that despite tremendous amount of investments made in clean energy, 60% of electricity generated in the US are still from traditional sources like natural gas, coal and petroleum.


```{r}
colnames(zeosyearly2005_2022)[12] <- "ElectricityEndUseTotal"
zzleosyearly2005_2022eu <- ggplot(zeosyearly2005_2022, aes(x=Month,y = ElectricityEndUseTotal,group=1)) + geom_line(color="green")+ theme_bw()+labs(title="United States Total Electricity End Use 2005 - 2022", y= "Total Electricity End Use (Million Kilowatt Hours)",x="Year")
zzleosyearly2005_2022eu
```

### Transportation

We produced a line graph for the Gross Manufacturing Output in the United States from 2005 to 2021.

Finally we looked at the vehicle usage which is measure in million miles. We normalized the data for uniformity in comparison, as the magnitude of data differ significantly between the different sectors. We found that over the ten year observation period, air travel millage dropped 16%. In the mean time, travel by rail increased 25%, and total highway millage increased 5%. We speculate that this is not related to 911, instead, it is due to the poor customer service provided by airlines, and increased airline fares, as air travel millage peaked in 2007, at a 20% increase from 2001. 

```{R}
colnames(ztransyearly1990_2015)[1] <- "Year"
z2transyearly1990_2015 <- ztransyearly1990_2015 %>%
  pivot_longer(!Year, names_to = "type", values_to = "value")%>%
  filter(type %in% c("air_carrier_domestic_all_services","highway_total","commuter_rail")) %>%
  mutate(Year = as.numeric(Year), value)
zztransyearly2005_2015 <- z2transyearly1990_2015%>%
  filter(Year>=2005)%>%
  mutate(value = gsub(",","",value))%>%
  mutate(value=gsub("\\(R\\) ","",value))%>%
  mutate(value=as.numeric(value))
ggplot(zztransyearly2005_2015, aes(x=Year, y=value, color=type,group=type))+geom_line()+theme_bw() + ylab("Annual Vehicle Miles (Millions)")
zztransyearly2005_2015 <- zztransyearly2005_2015%>%
  group_by(type)%>%
  mutate(value=((value - min(value))/(max(value)-min(value))))
ggplot(zztransyearly2005_2015, aes(x=Year,y=value,color=type,group=type))+geom_line()+theme_bw()+ylab("Normalized vehicle miles")
zztranshighway <- zztransyearly2005_2015 %>%
  filter(type=="Highway, total")
zztransair <- zztransyearly2005_2015 %>%
  filter(type=="Air carrier, domestic, all services")
zztransrail <- zztransyearly2005_2015 %>%
  filter(type=="Commuter rail")
```



-----




```{R}

#loading the data
data = read.csv("https://raw.githubusercontent.com/JackBenadon/Stat-380-group-project/main/data.csv", header = T)
#removing NA values
data <- data %>% 
    na.omit() 
#removing the (R) in the commuter.rail column
data$Commuter.rail[11] <- 372
#removing the commas in Highway..total because its special 
data$Highway..total <- gsub(",", "", data$Highway..total)
# making the all the columns into numeric variables
data$Commuter.rail <- as.numeric(sub(",","",data$Commuter.rail))
data$Air.carrier..domestic..all.services <- as.numeric(sub(",","",data$Air.carrier..domestic..all.services))
data$Highway..total <- as.numeric(data$Highway..total)
#making sure the transport data is only one column
data$transport <- data$Air.carrier..domestic..all.services + data$Commuter.rail + data$Highway..total
``` 


```{R}
#initializing NN
NNet <- nn_module(
  initialize = function(input_size, hidden_size, output_size) {
    self$input_size <- input_size
    self$hidden_size <- hidden_size
    self$output_size <- output_size
    
    self$f1 <- nn_linear(input_size + hidden_size, hidden_size)
    self$f2 <- nn_linear(hidden_size, output_size)
    self$activation <- nn_tanh()
  },
  
 forward = function(x) {
    hidden <- self$f1(x) %>% self$activation()
    output <- self$f2(hidden)
    list(output, hidden)
  }
)

nnet_fit <- NNet %>% 
  setup(
    loss = nn_mse_loss(),
    optimizer = optim_adam, 
    metrics = list(luz_metric_rmse())
  ) %>%
  set_hparams(input_size = 4, 
              hidden_size = 32, 
              output_size = 1) %>% 
  set_opt_hparams(lr = 0.005) %>% 
  fit(
    data = list(
      x = model.matrix(co2 ~ transport + ElectricityEndUseTotal + GOMA + gdp  , data = data),
      y = data %>% select(co2) %>% as.matrix
    ),
    
    dataloader_options = list(shuffle = TRUE, num_workers = 0),
    verbose = FALSE # Change to TRUE while tuning. But, set to FALSE before submitting
  )
  

# Get the weights of the linear layers
f1_weights <- nnet_fit$model$f1$weight
f2_weights <- nnet_fit$model$f2$weight
    
# Compute the magnitude of the weights and sum across input dimensions
f1_importance <- colSums(abs(f1_weights))
f2_importance <- abs(f2_weights)

# Combine the weights and their indices into a data frame
importance_df <- data.frame(
  variable = c(names(nnet_fit$model$f1$bias), "hidden", "output"),
  importance = c(f1_importance, f2_importance)
)

# Sort the data frame in descending order of importance
importance_df <- importance_df[order(-importance_df$importance), ]

# Print the top 5 most important variables
head(importance_df, 5)
  
  
```

```{r}
 NNet <- nn_module(
     initialize = function(p, q1, q2, q3){
       self$hidden1 <- nn_linear(p,q1)
       self$hidden2 <- nn_linear(q1,q2)
       self$hidden3 <- nn_linear(q2,q3)
       self$output <- nn_linear(q3,1)
       self$activate <- nn_relu()
     },
     forward = function(x){
       x%>%
         self$hidden1() %>%
         self$activate() %>%
         self$hidden2() %>%
         self$activate() %>%
         self$hidden3() %>%
         self$activate() %>%
         self$output()
     }
 )
 
 nnet_fit <- NNet %>% 
   setup(
     loss = nn_mse_loss(), optimizer = optim_adam
   ) %>%
   set_hparams(
     p=12,q1=32,q2=16,q3=8
   ) %>%
   set_opt_hparams(
     lr=0.03
     ) %>%
   fit(
     data=list(model.matrix(co2 ~ transport + ElectricityEndUseTotal + GOMA + gdp  , data = data),
               data%>%select(co2)%>%as.matrix()),
     epochs=20,
     verbose = FALSE # Change to TRUE while tuning. But, set to FALSE before submitting
 
   )


```



```{r}
library(xgboost)

data <- as.data.frame(data)

train <- data[1:9,]
test <- data[10:11,]

train_Dmatrix <- train %>% 
                 dplyr::select(transport,gdp,GOMA,ElectricityEndUseTotal) %>% 
                 as.matrix()
                 
 
pred_Dmatrix <- test %>% 
                dplyr::select(transport,gdp,GOMA,ElectricityEndUseTotal) %>% 
                as.matrix()
 
targets <- train$co2

#Cross-validation
library(caret)
 
xgb_trcontrol <- trainControl(
  method = "cv", 
  number = 5,
  allowParallel = TRUE, 
  verboseIter = FALSE, 
  returnData = FALSE
)
 
#Building parameters set
xgb_grid <- base::expand.grid(
  list(
    nrounds = c(5,10,50, 100,200,500,1000),
    max_depth = c(1:6), 
    colsample_bytree = 1, 
    eta = 0.5,
    gamma = 0,
    min_child_weight = 1,  
    subsample = 1)
)

#Building the model
model_xgb <- caret::train(
  train_Dmatrix,targets,
  trControl = xgb_trcontrol,
  tuneGrid = xgb_grid,
  method = "xgbTree",
  nthread = 10,
  verbosity=0
)

model_xgb$bestTune

#Making the variables used in forecast object 
fitted <- model_xgb %>%
  stats::predict(train_Dmatrix) %>%
  stats::ts(start = c(2005,1),frequency = 1)
 
ts_co2 <- ts(targets,start=c(2005,1),frequency=1)
forecast_xgb <- model_xgb %>% stats::predict(pred_Dmatrix)
forecast_ts <- ts(forecast_xgb,start=c(2014,1),frequency=1)
 
#Preparing forecast object
forecast_co2 <- list(
  model = model_xgb$modelInfo,
  method = model_xgb$method,
  mean = forecast_ts,
  x = ts_co2, 
  fitted = fitted,
  residuals = as.numeric(ts_co2) - as.numeric(fitted)
)
class(forecast_co2) <- "forecast"

#The function to convert decimal time label to wanted format
library(lubridate)
date_transform <- function(x) {format(date_decimal(x), "%Y")}
#Making a time series varibale for observed data
observed_values <- ts(test$co2,start=c(2014,1),frequency=1)

#Plot forecasting
library(ggplot2)
library(forecast)
 
autoplot(forecast_co2)+
  autolayer(forecast_co2$mean,series="Predicted",size=0.75) +
  autolayer(forecast_co2$x,series ="Train",size=0.75 ) +
  autolayer(observed_values,series = "Observed",size=0.75) +
  scale_x_continuous(labels =date_transform,breaks = seq(2005,2014,1) ) +
  guides(colour=guide_legend(title = "Time Series")) +
  ylab("CO2 Emissions") + xlab("Time") +
  ggtitle("") +
  theme_bw()
```


```{r}
#Feature importance
library(Ckmeans.1d.dp)
 
xgb_imp <- xgb.importance(
  feature_names = colnames(train_Dmatrix),
  model = model_xgb$finalModel)
 
xgb.ggplot.importance(xgb_imp,n_clusters = c(2))+ 
  ggtitle("") +
  theme_bw()+
  theme(legend.position="none")
 
xgb_imp$Importance
```




